// Generated by Kodagen cinematic-site-generator
// Style: S11 Architectural Product | Archetype: G | Voice: V6 Technical Premium
// White background + dark gray secondary + warm amber Sahara accent

export const siteConfig = {
  brand: {
    name: "SaharaOps",
    wordmark: "SaharaOps",
    tagline: "Operational readiness consulting for organizations that intend to scale.",
    fullName: "SaharaOps Operational Readiness Consulting",
    description:
      "Operational readiness consulting for startups, SMEs, and NGOs across Africa, the Middle East, Europe, and Asia."
  },
  contact: {
    email: "hello@saharaops.com",
    phone: "+234 800 SAHARA",
    location: "Lagos · Nairobi · London",
    address: {
      city: "Lagos",
      country: "Nigeria",
      countryCode: "NG"
    },
    socials: {
      linkedin: "https://linkedin.com/company/saharaops"
    }
  },
  headerVariant: "split-edges",
  motion: {
    intensity: "low",
    cursorFollower: false,
    scrollProgress: true
  },
  colors: {
    luminance: "light",
    bg: {
      primary: "#FFFFFF",
      secondary: "#F5F4F1",
      tertiary: "#E8E6E1",
      accent: "#1A1A1A"
    },
    text: {
      hero: "#1A1A1A",
      body: "#2C2C2C",
      muted: "#6B6B6B",
      eyebrow: "#C77C44",
      inverse: "#FAFAFA"
    },
    accent: {
      primary: "#C77C44",
      soft: "#EAD9B7"
    },
    cardOverlay: {
      tint: "rgba(255,255,255,0.78)",
      blur: "xl",
      border: "1px solid rgba(26,26,26,0.10)"
    }
  },
  hero: {
    eyebrow: "Operational Readiness Consulting",
    h1: [
      { text: "Operating systems for ", emphasis: false, italic: false },
      { text: "organizations", emphasis: true, italic: true },
      { text: " that intend to scale.", emphasis: false, italic: false }
    ] as Array<{ text: string; emphasis: boolean; italic: boolean }>,
    h1Plain:
      "Operating systems for organizations that intend to scale.",
    subhead:
      "We build the processes, structures, and operating cadences that turn strategy into measurable execution — for startups preparing for investors, SMEs scaling into new markets, and NGOs delivering accountable impact.",
    primaryCta: { label: "Book a Consultation", href: "/consultation" },
    secondaryCta: { label: "View Services", href: "/services" }
  },
  whyUs: {
    eyebrow: "Why SaharaOps",
    h2: "Strategy and execution rarely fail apart. They fail at the seam.",
    body:
      "Most growth-stage organizations don't lack vision. They lack the operating backbone — the processes, structures, and accountabilities that translate strategy into shipped work. We close that gap. SaharaOps brings full visibility into how your organization actually runs, then designs the practical systems that strengthen resilience and unlock the next stage of growth.",
    pillars: [
      {
        title: "Cross-sector",
        body:
          "Startups, established SMEs, and mission-driven NGOs — including UN-supported programmes."
      },
      {
        title: "Global perspective",
        body:
          "Engagements delivered across Africa, the Middle East, Europe, and Asia, adapted to local realities."
      },
      {
        title: "Proven outcomes",
        body:
          "Documented results in process optimization, scaling, and investor readiness."
      },
      {
        title: "Tailored, not templated",
        body:
          "We design and help implement — not just advise. Solutions fit your stage, size, and mission."
      }
    ]
  },
  services: {
    eyebrow: "Our Services",
    h2: "Tailored consulting for startups, SMEs, and NGOs.",
    intro:
      "Three pathways, one philosophy: build the operating systems that match where you are now and where you intend to be next.",
    items: [
      {
        slug: "startups",
        number: "01",
        kicker: "For Startups",
        name: "Build structure to scale and attract investment.",
        body:
          "Operational readiness assessments, process optimization, investor-readiness support, and scaling playbooks for high-growth ventures.",
        bullets: [
          "Operational Readiness Assessments",
          "Process Optimization & Automation",
          "Investor Readiness Support",
          "Scaling & Market Expansion",
          "Agile Project & Change Management"
        ],
        outcomes: [
          "Lower burn rate",
          "Faster scaling",
          "Stronger investor confidence",
          "Team alignment"
        ],
        ctaLabel: "Explore Startup Services",
        href: "/services/startups"
      },
      {
        slug: "smes",
        number: "02",
        kicker: "For SMEs",
        name: "Streamline operations and scale sustainably.",
        body:
          "Business process optimization, organizational design, risk management, and expansion strategy for established small and mid-sized firms.",
        bullets: [
          "Business Process Optimization",
          "Organizational Design & Talent Development",
          "Risk Management & Resilience",
          "Expansion into New Markets",
          "Leadership Coaching"
        ],
        outcomes: [
          "Cost reduction",
          "Stronger structure & leadership",
          "Sustainable growth",
          "Increased productivity"
        ],
        ctaLabel: "Explore SME Services",
        href: "/services/smes"
      },
      {
        slug: "ngos",
        number: "03",
        kicker: "For NGOs & Nonprofits",
        name: "Strengthen accountability, improve impact.",
        body:
          "Knowledge management, donor reporting, governance, and program scaling for mission-driven organizations.",
        bullets: [
          "Knowledge Management Systems",
          "Donor & Stakeholder Reporting",
          "Process Documentation & Governance",
          "Program Scaling & Digital Transformation"
        ],
        outcomes: [
          "Streamlined operations",
          "Donor confidence",
          "Measurable program impact",
          "Stronger governance"
        ],
        ctaLabel: "Explore NGO Services",
        href: "/services/ngos"
      }
    ]
  },
  outcomes: {
    eyebrow: "Proven Outcomes",
    h2: "From scaling startups to strengthening NGOs — measurable, documented results.",
    items: [
      { label: "Onboarding cycle", before: "6 weeks", after: "3 days", note: "SEMA therapist onboarding" },
      { label: "Burn-rate trimmed", value: "32%", note: "Average across startup engagements" },
      { label: "Continents served", value: "4", note: "Africa · Middle East · Europe · Asia" },
      { label: "Engagements led", value: "40+", note: "Across startups, SMEs, and NGOs" }
    ]
  },
  trustedBy: [
    "International Trade Centre (UN/WTO)",
    "Ennovate Ventures",
    "UN Women — Europe & Central Asia",
    "SEMA",
    "Impakt Advisors",
    "Card Sugar"
  ],
  testimonials: [
    {
      quote:
        "When we engaged Chisobem, SEMA had a product and almost non-existent process. Working with SaharaOps got us the systems we needed. We scaled the time to onboard therapists from six weeks to two — and now to three days.",
      author: "Founder",
      org: "SEMA"
    },
    {
      quote:
        "Chisobem was critical to structuring our business operations so the management team could focus on delivering work and managing client relationships. The systems she helped us build across Sales, IT, Operations, AR, and HR were key contributors to our ability to eventually sell the business.",
      author: "Founder",
      org: "Impakt Advisors"
    },
    {
      quote:
        "Thank you for helping us build much-needed structure around this business, and helping me understand the actual workings and the production costs associated with it. I now have a document I can consult to clearly see our position.",
      author: "Founder",
      org: "Card Sugar"
    },
    {
      quote:
        "Chisobem is an exceptional growth-hacking expert. Her guidance has enabled several of our portfolio ventures to attract follow-on investment and scale sustainably.",
      author: "Founder",
      org: "Ennovate Ventures"
    }
  ],
  process: {
    eyebrow: "How It Works",
    h2: "A four-step engagement, designed for outcomes — not deliverables.",
    steps: [
      {
        number: "01",
        title: "Discovery",
        body:
          "We learn the shape of your organization — goals, friction points, hidden costs, and what 'better' looks like from the inside."
      },
      {
        number: "02",
        title: "Assessment",
        body:
          "We map current systems, processes, and gaps against your stated and unstated future state."
      },
      {
        number: "03",
        title: "Implementation",
        body:
          "We design and roll out tailored solutions — not slide decks, but working systems, with your team in the room."
      },
      {
        number: "04",
        title: "Handover",
        body:
          "We equip your team with the tools, documentation, and training to operate the new system independently."
      }
    ]
  },
  cta: {
    eyebrow: "Next Step",
    h2: "Ready to build your operational backbone?",
    body:
      "Book a consultation. We'll spend an hour understanding what's actually happening inside your organization — and what would change if it ran differently.",
    primaryCta: { label: "Book a Consultation", href: "/consultation" },
    secondaryCta: { label: "View Services", href: "/services" }
  },
  about: {
    eyebrow: "About SaharaOps",
    h1: "Built on the belief that growth requires structure.",
    body:
      "SaharaOps was founded on a single, repeatedly observed truth: most organizations don't fail because the strategy was wrong. They fail because the operating system underneath couldn't carry it. We specialize in operational readiness consulting — designing the processes, governance, and systems that let ambitious organizations execute reliably across stages, geographies, and stakeholders.",
    mission:
      "To equip startups, SMEs, and NGOs with the operational systems that turn intention into measurable outcomes.",
    founder: {
      name: "Chisobem Nwokedi",
      role: "Founder & Principal Consultant",
      credentials: [
        "Certified Agile Practitioner",
        "Project Management Professional (PMP)",
        "Scrum Product Owner",
        "Cross-sector engagements across four continents"
      ],
      bio:
        "Chisobem leads SaharaOps. She has spent the last decade partnering with founders, executives, and nonprofit leaders to install the operating systems behind growth — from fast-moving startups to established SMEs and UN-supported NGO programmes."
    },
    differentiators: [
      "Cross-sector expertise — from startups to UN-supported programmes",
      "Global perspective — four continents, locally adapted",
      "Documented, measurable results in process optimization and scaling",
      "Tailored solutions — we design and help implement, not just advise"
    ]
  },
  footer: {
    variant: "FT6",
    brandStatement:
      "Operating systems for organizations that intend to scale.",
    ctaHeadline: "Let's build your operational backbone.",
    contactEmail: "hello@saharaops.com",
    columns: [
      {
        heading: "Services",
        items: [
          { label: "For Startups", href: "/services/startups" },
          { label: "For SMEs", href: "/services/smes" },
          { label: "For NGOs", href: "/services/ngos" },
          { label: "All Services", href: "/services" }
        ]
      },
      {
        heading: "Company",
        items: [
          { label: "About", href: "/about" },
          { label: "Resources", href: "/resources" },
          { label: "Consultation", href: "/consultation" },
          { label: "Contact", href: "/contact" }
        ]
      },
      {
        heading: "Trusted by",
        items: [
          { label: "International Trade Centre (UN/WTO)", href: "#" },
          { label: "Ennovate Ventures", href: "#" },
          { label: "UN Women — Europe & Central Asia", href: "#" }
        ]
      }
    ],
    footnotes: [
      { label: "Privacy Policy", href: "/privacy" },
      { label: "Terms of Service", href: "/terms" }
    ]
  },
  seo: {
    siteUrl: "https://saharaops.com",
    siteName: "SaharaOps",
    locale: "en_US",
    defaultTitle: "SaharaOps — Operational Readiness Consulting for Startups, SMEs & NGOs",
    defaultDescription:
      "SaharaOps helps Startups, SMEs, and NGOs across Africa, the Middle East, Europe, and Asia scale with operational readiness, process optimization, and investor readiness consulting.",
    twitterHandle: "@saharaops"
  },
  generationManifest: {
    archetype: "G",
    style: "S11",
    voiceFamily: "V6",
    sceneVariant: "V1",
    motionVariant: "M2",
    cardVariant: "CV4",
    headerVariant: "split-edges",
    footerVariant: "FT6",
    heroOverlay: "HO2",
    heroTextPattern: "H3",
    heroEntrance: "E2",
    colorVariant: "white-charcoal-amber",
    industryObject: "minimalist operational architecture model on a white pedestal",
    aboutVariant: "AB3",
    contactVariant: "CT4",
    benefitsVariant: "BN4",
    statsVariant: "ST1",
    testimonialsVariant: "TS1",
    ctaVariant: "CTA1"
  }
} as const;

export type SiteConfig = typeof siteConfig;
